name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  linux:
    name: Linux Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Jar File
      run: |
        cd src
        bash run.sh -a
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: all-spigot-NMS-Linux.jar
        path: extracted_files/all-spigot-nms.jar
  windows:
    name: Windows Test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Jar File
      run: |
        cd src
        bash run.sh -a
  mac:
    name: Mac Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Jar File
      run: |
        cd src
        bash run.sh -a
